### PR TITLE
after change on code Booking notes work properly.

### PR DESCRIPTION
**Pull request by krishna120801**
issue number 31 completed.

### CODE REVIEW

**Comment by krishna120801** [comment]
task 18 and plus icon positioning completed.

**Comment by epicdeepak** [comment]
@krishna120801 resolve this conflict

**Review by epicdeepak — CHANGES_REQUESTED** [review]
image
we don't need this footer once we logged in

**Comment by epicdeepak** [comment]
krishna, resolve the conflicts.

**Pull request merged**
